name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Check
        run: ls

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            triangle.exe
